cove360: templates: base.html: logo link.
OpenDataServices/cove pull request #1304
Opened 2020-10-09 08:33 UTC by BibianaC

Link logo image to 360 main webpage.
https://github.com/OpenDataServices/cove/issues/779

2020-10-09 08:51 UTC, BibianaC commented
![](https://github.trello.services/images/mini-trello-icon.png) [Logo to link to homepage](https://trello.com/c/LfVjKcsr/115-logo-to-link-to-homepage)

2020-10-14 08:27 UTC, rhiaro requested changes

2020-10-14 08:27 UTC, rhiaro commented on cove_360/templates/cove_360/base.html
> +      <a id="360_giving_logo" href="http://www.threesixtygiving.org/">
```suggestion
      <a id="360_giving_logo" href="https://www.threesixtygiving.org/">
```

2020-10-14 08:27 UTC, rhiaro commented on cove_360/tests_functional.py
> +    assert href == 'http://www.threesixtygiving.org/'
```suggestion
    assert href == 'https://www.threesixtygiving.org/'
```

2020-10-14 10:09 UTC, BibianaC commented on cove_360/templates/cove_360/base.html
> +      <a id="360_giving_logo" href="http://www.threesixtygiving.org/">
Thanks @rhiaro for the suggestion.

2020-10-14 10:09 UTC, BibianaC commented on cove_360/tests_functional.py
> +    assert href == 'http://www.threesixtygiving.org/'
Thanks @rhiaro for the suggestion.

2020-10-14 10:18 UTC, rhiaro approved these changes

2020-10-14 10:19 UTC, merged